### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Khhs167** [MCPI-Devs/MCPIL#20]
It installs, then there is a module missing. I do not remember the name, but it was something like  mcpidocker or something.

**Comment by Alvarito050506** [comment]
Hello @Khhs167!

I'm not sure how you installed MCPIL, since it should install MCPI-Docker as a dependency, but anyways, please use [MCPIL-R](https://github.com/MCPI-Devs/MCPIL-R), since this project is currently dead/unsupported. MCPIL-R is a "reboot" of MCPIL, with better code and some cool features, like an easy installation method and full integration with MCPI-Docker.

Anyways, thanks for your interest in the project!
