### ISSUE TITLE
ModuleNotFoundError: No module named 'mcpicentral'

### ISSUE THREAD

**Issue by NikZapp** [MCPI-Devs/MCPIL#5]
I was getting this error while trying to download mcpil
First i downloaded the latest python version (3.9) because i had 3.5
Then i tried running it, got a ModuleNotFound error
As said in your guide, i began to download brew, but the right ruby version could not be found by brew, soi found [this](https://gist.github.com/blacktm/8302741) guide and it worked.
Then i proceeded with the Troubleshooting instructions, custompython was downloading for too long and i left it overnight.
The next morning i checked it, and it still didn't work:
`pi@raspberrypi:~ $ python3.9 /usr/bin/mcpil`
`Traceback (most recent call last):`
`  File "/usr/bin/mcpil", line 39, in <module>`
`    from mcpicentral import APIClient`
`ModuleNotFoundError: No module named 'mcpicentral'`
Maybe you can attach the module files to the program.

**Comment by NikZapp** [comment]
i am using `python3.9 /usr/bin/mcpil` because if i use just `mcpil` it will try to run it with python 3.5

**Comment by Alvarito050506** [comment]
Hello @NikZapp!

Did you install MCPIL from our Debian repos as described [here](https://github.com/MCPI-Devs/MCPIL#installation)? I would really suggest you to do so, since it's the easiest way to get any MCPIL version, and the dependencies management is left to the `apt` package manager.

By the way, one of the dependencies of the last MCPIL update, [minecraft-pi-docker](https://gitea.thebrokenrail.com/TheBrokenRail/minecraft-pi-docker) is currently broken (causes segfaults) in RPis, so I would recommend you installing an older version, which not depends on that package (yes, it has reduced features, but we're working at it :wink:).
```sh
# If you didn't add the repository yet
curl -s https://packagecloud.io/install/repositories/Alvarito050506/mcpi-devs/script.deb.sh | sudo bash

# Now the actual installation
sudo apt-get install mcpil=0.6.2 # v0.6.2 is the latest update which does not depend on mcpi-docker
```
These commands _should_ download, set-up and install everything needed to run MCPIL.

Feel free to tell me if you have any other problem, or if this one persists.

**Comment by NikZapp** [comment]
I did, in fact run these commands but it still doesn't work.
Gonna retry right now, maybe now it will fix it

**Comment by NikZapp** [comment]
Wait no those are new commands

**Comment by NikZapp** [comment]
`pi@raspberrypi:~ $ # If you didn't add the repository yet`
`pi@raspberrypi:~ $ curl -s https://packagecloud.io/install/repositories/Alvarito050506/mcpi-devs/script.deb.sh | sudo bash`
`Detected operating system as raspbian/stretch.`
`Checking for curl...`
`Detected curl...`
`Checking for gpg...`
`Detected gpg...`
`Running apt-get update... done.`
`Installing apt-transport-https... done.`
`Installing /etc/apt/sources.list.d/Alvarito050506_mcpi-devs.list...done.`
`Importing packagecloud gpg key... done.`
`Running apt-get update... done.`
`The repository is setup! You can now install packages.`
`pi@raspberrypi:~ $ `
`pi@raspberrypi:~ $ # Now the actual installation`
`pi@raspberrypi:~ $ sudo apt-get install mcpil=0.6.2 # v0.6.2 is the latest update which does not depend on mcpi-docker`
`Reading package lists... Done`
`Building dependency tree       `
`Reading state information... Done`
`E: Version '0.6.2' for 'mcpil' was not found`

**Comment by Alvarito050506** [comment]
Oh, my fault, the version is `0.6.1`, sorry...

**Comment by NikZapp** [comment]
Thanks! It worked!

**Comment by nobody5050** [comment]
Awesome!

**Comment by Alvarito050506** [comment]
No problem! And yes!

**Comment by NikZapp** [comment]
I think i have the most amount of issues because there is a new one
